Fix lint errors and kuttl tests

diff --git a/tests/kuttl/tests/designate_tls/05-assert.yaml b/tests/kuttl/tests/designate_tls/05-assert.yaml
--- a/tests/kuttl/tests/designate_tls/05-assert.yaml
+++ b/tests/kuttl/tests/designate_tls/05-assert.yaml
@@ -157,21 +157,6 @@ spec:
         - /usr/local/bin/container-scripts/init.sh
         command:
         - /bin/bash
-        env:
-        - name: AdminPassword
-          valueFrom:
-            secretKeyRef:
-              key: DesignatePassword
-              name: osp-secret
-        - name: TransportURL
-          valueFrom:
-            secretKeyRef:
-              key: transport_url
-              name: rabbitmq-transport-url-designate-designate-transport
-        - name: DatabaseHost
-          value: openstack.designate-kuttl-tests.svc
-        - name: DatabaseName
-          value: designate
         imagePullPolicy: IfNotPresent
         name: init
         resources: {}
@@ -249,3 +234,13 @@ spec:
   selector:
     service: designate
   type: ClusterIP
+---
+apiVersion: kuttl.dev/v1beta1
+kind: TestAssert
+commands:
+  - script: |
+      if ! oc get -n $NAMESPACE secret -o json designate-central-config-data | jq '.data["designate.conf"] | @base64d' | sed -e 's/\\n/\n/g' | grep ^backend_url.*redis.*ssl.true;
+      then
+          echo "Configuration of backend_url failed"
+          exit 1
+      fi
